backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "product"
    label: "Продукт"
    folder: "content/products"
    create: true
    slug: "index"
    media_folder: ""
    public_folder: ""
    path: "{{title}}/index"
    editor:
      preview: false

    filter: {field: "Вид на продукт", value: "Машина 1"}
    fields:
      - { label: "Име", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

    filter: {field: "Вид на продукт", value: "Машина 2"}
    fields:
      - { label: "Име", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "markdown" }
      - { label: "Мощност", name: "power", widget: "string" }
      - { label: "Дължина", name: "length", widget: "string" }
      - { label: "Височина", name: "height", widget: "string" }
      - { label: "Ширина", name: "width", widget: "string" }
      - { label: "Тегло", name: "weight", widget: "string" }
      - { label: "Капацитет", name: "capacity", widget: "string" }
